### ISSUE TITLE
Too many bugs to mention them all

### ISSUE THREAD

**Issue by roncemer** [ianneub/pg_dump-to-s3#3]
Your run.sh needs to be completely re-written.
1) Forcing POSTGRES_HOST_OPTS to be empty, but using that in the pg_dump command instead of the specified environment variables.  If POSTGRES_HOST_OPTS is to be used, run.sh shouldn't be setting it to empty before using it.
2) Calling date more than once (the date, hour or minute could change between calls)
3) No way to format the date/time suffix on the file.  Should be able to specify the date format string (+ formatting) and whether to use UTC time zone

**Comment by ianneub** [comment]
Thanks @roncemer good catch on `POSTGRES_HOST_OPTS`. I forgot to remove that the last time I updated the script. I've pushed an update that addresses that and also fixes the `PGDATABASE` ENV var not being used.

I hardly think the script needs to be "completely re-written" though. If you'd like to add the date features that would be great. I'd be happy to accept a PR.
